### ISSUE TITLE
Stylowanie komponentów z użyciem TailwindCSS

### ISSUE THREAD

**Issue by DCzajkowski** [vuejs-poland/krakow#3]
## Stylowanie komponentów z użyciem TailwindCSS

https://www.meetup.com/Vue-js-Poland/events/264551943/

## Krótki opis

TailwindCSS jest stanowczo nowym framework'iem do stylowania. Prezentacja skupiłaby się na przedstawieniu Tailwind'a szerszej publiczności oraz jego zastosowaniu podczas tworzenia komponentów w Vue.

Planuję podzielić talk na dwie części — krótkie wprowadzenie i live coding.

## Długość prezentacji

30-40 minut

## Coś o Tobie

Jestem studentem informatyki na AGH oraz pracuję dla Airly, polskiego start-up'u, jako programista Vue.

## Twoje doświadczenie na meetupach/konferencjach

Prezentacje dawałem na Wake Up (konferencja studencka na AGH) oraz [na meet-up'ie w Tokio](https://twitter.com/CzajkowskiDarek/status/1172365397665804294) podczas stażu w Mercari. Często uczęszczam na hackathony i zawsze prezentuję owoce pracy zespołu.

**Comment by shentao** [comment]
Rewelacja @DCzajkowski! Do zobaczenia!
