### ISSUE TITLE
Pierwsza strona instytucji publicznej w Vue.js – jak powstała, jakie napotkaliśmy problemy i jak je rozwiązaliśmy

### ISSUE THREAD

**Issue by IgorPodlawski** [vuejs-poland/krakow#4]
## Tytuł prezentacji
Pierwsza strona instytucji publicznej w Vue.js – jak powstała, jakie napotkaliśmy problemy i jak je rozwiązaliśmy

https://www.meetup.com/pl-PL/Vue-js-Poland/events/264551943/

## Krótki opis
O tym jak zbudowaliśmy najprawdopodobniej pierwszą stronę instytucji publicznej w Vue.js (RCKiK w Katowicach www.rckik-katowice.pl), jakie problemy napotkaliśmy i jak j rozwiązaliśmy. Będzie też krótko o tym jak pracujemy z API WordPressa w tym lub w innych projektach.

## Długość prezentacji
20 - 30 min

## Coś o Tobie
Front-end developer, wykładowca w Coders Lab oraz właściciel firmy Software Things, członek społeczności Coding Dojo Silesia. Dorywczo autor artykułów w magazynie programista.

## (opcjonalnie) Twoje doświadczenie na meetupach/konferencjach
0 doświadczenia :), poza prowadzeniem kilku wykładów dla CodersLabu i poza organizacją Coding Dojo Silesia w Gliwicach (gdzie się koduje, a nie rozmawia :)) także wszelkie porady i uwagi mile widziane.

**Comment by shentao** [comment]
Zaakceptowany. Do zobaczenia!
