### ISSUE TITLE
Higher Order Components - wzorzec dekoratora i jego użycie we Vue

### ISSUE THREAD

**Issue by bleto** [vuejs-poland/krakow#5]
## Krótki opis
Cel prezentacji to przedstawienie ogólnych założeń dotyczących koncepcji HOC oraz wykorzystania wzorca dekoratora we Vue. Przybliżę jak można zaimplementować taki wzorzec zgodnie z nowymi założeniami frameworka, oraz jakich rzeczy ewentualnie powinniśmy się wystrzegać przy jego tworzeniu.

## Długość prezentacji
20-30 minut
## Coś o Tobie
Programista od ponad 7 lat, swoją przygodę zacząłem od PHP, a aktualnie skupiam się głównie na JS. Obecnie pracuję w firmie Strix jako front-end developer gdzie współtworzę opensourcową aplikację typu PIM o nazwie [Ergonode](https://ergonode.com).

**Comment by shentao** [comment]
Zaakceptowany. Do zobaczenia!
