### ISSUE TITLE
Vue.js Krk Meetup #2 - Sloty, sposób na w pełni customizowalny komponent w Vue

### ISSUE THREAD

**Issue by pspaczek** [vuejs-poland/krakow#6]
## Tytuł prezentacji
Sloty, sposób na w pełni customizowalny komponent w Vue

https://www.meetup.com/pl-PL/Vue-js-Poland/events/264551943/
## Krótki opis
Opowiem o tym jak potencjał ma używanie slotów w Vue oraz o ich ograniczeniach. W oparciu o doświadczenia zdobyte przy tworzeniu UI-owej libki, odpowiem na pytanie jak poradzić sobie z ograniczeniami i jak moim zdaniem najefektywniej z nimi pracować przy tworzeniu cutomizowalnych komponentów.

## Długość prezentacji
~20min
## Coś o Tobie
Front-end developer w Divante, Wrocławskim eCommerce Software House. Pracuję nad rozwojem Storefront UI, pierwszej UI-owej libki Vue.js dla eCommerce oraz VueStorefront frontendem PWA dla eCommerce.

**Comment by shentao** [comment]
Zaakceptowany. Do zobaczenia!
